import {
  buildProjectOverview,
  buildConventionsSection,
  buildFrameworkGuidelines,
} from './shared.js';
import { buildEnhancedSections } from './enhanced.js';

/**
 * Generate .aider.conventions.md
 * Aider reads conventions from markdown files specified in config.
 * We generate a conventions file and an .aider.conf.yml pointing to it.
 */
export function generateAiderConventions(scan) {
  const sections = [];

  sections.push(`# Aider Conventions — ${scan.project.name}`);
  sections.push(`# Generated by onboardai — ${new Date().toISOString().split('T')[0]}`);
  sections.push('');

  sections.push(buildProjectOverview(scan));
  sections.push(buildConventionsSection(scan));

  const fwGuidelines = buildFrameworkGuidelines(scan);
  if (fwGuidelines) sections.push(fwGuidelines);

  sections.push('## Rules');
  sections.push('');
  sections.push('- Follow existing patterns in the codebase');
  sections.push('- Write clean, readable code');
  sections.push('- Handle errors properly');

  if (scan.testing.runner) {
    sections.push(`- Write tests with ${scan.testing.runner}`);
  }

  sections.push('');

  // LLM-enhanced sections
  const enhanced = buildEnhancedSections(scan);
  if (enhanced) sections.push(enhanced);

  return {
    path: '.aider.conventions.md',
    content: sections.join('\n'),
  };
}
