import {
  buildProjectOverview,
  buildStructureSection,
  buildConventionsSection,
  buildTestingSection,
  buildFrameworkGuidelines,
} from './shared.js';
import { buildEnhancedSections } from './enhanced.js';

/**
 * Generate CLAUDE.md file
 * Claude Code reads CLAUDE.md from the project root for context.
 * It supports a concise, direct instruction style.
 */
export function generateClaudeMd(scan) {
  const sections = [];

  // Header — Claude prefers direct, imperative instructions
  sections.push(`# CLAUDE.md — ${scan.project.name}`);
  sections.push('');
  sections.push(`> Auto-generated by onboardai on ${new Date().toISOString().split('T')[0]}`);
  sections.push('> Review and customize this file for your project.');
  sections.push('');

  // Project overview
  sections.push(buildProjectOverview(scan));

  // Structure
  sections.push(buildStructureSection(scan));

  // Framework guidelines
  const fwGuidelines = buildFrameworkGuidelines(scan);
  if (fwGuidelines) sections.push(fwGuidelines);

  // Conventions
  sections.push(buildConventionsSection(scan));

  // Testing
  sections.push(buildTestingSection(scan));

  // Build / run commands
  sections.push(buildCommandsSection(scan));

  // Style — Claude-specific: direct imperative instructions
  sections.push(`## Style Guidelines`);
  sections.push('');
  sections.push('When writing code for this project:');
  sections.push('');
  sections.push('- Match the existing code style and patterns');
  sections.push('- Be concise; avoid unnecessary abstractions');
  sections.push('- Prefer simple, readable solutions over clever ones');

  if (scan.languages.some(l => l.name === 'TypeScript')) {
    sections.push('- Always use TypeScript types; avoid `any`');
  }

  if (scan.testing.runner) {
    sections.push(`- Write tests using ${scan.testing.runner} for new functionality`);
  }

  sections.push('');

  // LLM-enhanced sections (only present when --enhance was used)
  const enhanced = buildEnhancedSections(scan);
  if (enhanced) sections.push(enhanced);

  // Placeholder
  sections.push('## Additional Context');
  sections.push('');
  sections.push('<!-- Add project-specific instructions, architecture decisions, -->');
  sections.push('<!-- domain knowledge, or anything Claude should know below.   -->');
  sections.push('');

  return {
    path: 'CLAUDE.md',
    content: sections.join('\n'),
  };
}

function buildCommandsSection(scan) {
  const lines = [];
  lines.push('## Common Commands');
  lines.push('');

  const pm = scan.packageManager;

  if (['npm', 'yarn', 'pnpm', 'bun'].includes(pm)) {
    const run = pm === 'npm' ? 'npm run' : pm;
    lines.push(`- Install dependencies: \`${pm} install\``);
    lines.push(`- Dev server: \`${run} dev\``);
    lines.push(`- Build: \`${run} build\``);

    if (scan.testing.runner) {
      lines.push(`- Run tests: \`${run} test\``);
    }
    if (scan.testing.e2e) {
      lines.push(`- E2E tests: \`${run} test:e2e\` (or check package.json scripts)`);
    }
    lines.push(`- Lint: \`${run} lint\``);
  } else if (pm === 'pip' || pm === 'poetry' || pm === 'pdm') {
    if (pm === 'poetry') {
      lines.push('- Install: `poetry install`');
      lines.push('- Run: `poetry run python <script>`');
      if (scan.testing.runner) lines.push(`- Test: \`poetry run pytest\``);
    } else if (pm === 'pdm') {
      lines.push('- Install: `pdm install`');
      lines.push('- Run: `pdm run <script>`');
    } else {
      lines.push('- Install: `pip install -r requirements.txt`');
      if (scan.testing.runner) lines.push(`- Test: \`pytest\``);
    }
  } else if (pm === 'go modules') {
    lines.push('- Build: `go build ./...`');
    lines.push('- Test: `go test ./...`');
    lines.push('- Run: `go run .`');
  } else if (pm === 'cargo') {
    lines.push('- Build: `cargo build`');
    lines.push('- Test: `cargo test`');
    lines.push('- Run: `cargo run`');
  } else if (pm === 'bundler') {
    lines.push('- Install: `bundle install`');
    if (scan.frameworks.some(f => f.name === 'Ruby on Rails')) {
      lines.push('- Dev server: `bin/rails server`');
      lines.push('- Console: `bin/rails console`');
      lines.push('- Test: `bin/rails test` or `bundle exec rspec`');
    }
  }

  lines.push('');
  return lines.join('\n');
}
