import {
  buildProjectOverview,
  buildStructureSection,
  buildConventionsSection,
  buildTestingSection,
  buildFrameworkGuidelines,
} from './shared.js';
import { buildEnhancedSections } from './enhanced.js';

/**
 * Generate .github/copilot-instructions.md
 * This is Copilot's official custom instructions file.
 * It should be concise and focused on code generation preferences.
 */
export function generateCopilotInstructions(scan) {
  const sections = [];

  sections.push(`# Copilot Custom Instructions — ${scan.project.name}`);
  sections.push('');
  sections.push(`<!-- Generated by onboardai on ${new Date().toISOString().split('T')[0]} -->`);
  sections.push('');

  // Project overview (brief)
  sections.push(buildProjectOverview(scan));

  // Conventions — Copilot benefits most from clear, short rules
  sections.push(buildConventionsSection(scan));

  // Framework guidelines
  const fwGuidelines = buildFrameworkGuidelines(scan);
  if (fwGuidelines) sections.push(fwGuidelines);

  // Testing
  sections.push(buildTestingSection(scan));

  // Code generation preferences
  sections.push('## Code Generation Preferences');
  sections.push('');
  sections.push('- Follow the existing patterns in this codebase');
  sections.push('- Prefer readability over brevity');
  sections.push('- Include error handling in generated code');

  if (scan.languages.some(l => l.name === 'TypeScript')) {
    sections.push('- Always include TypeScript types; do not use `any`');
    sections.push('- Add JSDoc comments to exported functions');
  }

  if (scan.testing.runner) {
    sections.push(`- When asked to write tests, use ${scan.testing.runner}`);
    if (scan.testing.patterns.length > 0) {
      sections.push(`- Test files follow the pattern: ${scan.testing.patterns[0]}`);
    }
  }

  sections.push('');

  // LLM-enhanced sections
  const enhanced = buildEnhancedSections(scan);
  if (enhanced) sections.push(enhanced);

  return {
    path: '.github/copilot-instructions.md',
    content: sections.join('\n'),
  };
}
