import {
  buildProjectOverview,
  buildStructureSection,
  buildConventionsSection,
  buildTestingSection,
  buildFrameworkGuidelines,
} from './shared.js';
import { buildEnhancedSections } from './enhanced.js';

/**
 * Generate .cursorrules file
 * Cursor uses a single markdown file at .cursorrules in the project root.
 */
export function generateCursorRules(scan) {
  const sections = [];

  // Header
  sections.push(`# Cursor Rules for ${scan.project.name}`);
  sections.push(`# Generated by onboardai — ${new Date().toISOString().split('T')[0]}`);
  sections.push('');

  // Project overview
  sections.push(buildProjectOverview(scan));

  // Structure
  sections.push(buildStructureSection(scan));

  // Framework-specific guidelines
  const fwGuidelines = buildFrameworkGuidelines(scan);
  if (fwGuidelines) sections.push(fwGuidelines);

  // Conventions
  sections.push(buildConventionsSection(scan));

  // Testing
  sections.push(buildTestingSection(scan));

  // General instructions
  sections.push(`## General Rules`);
  sections.push('');
  sections.push('- Follow existing code patterns and conventions in this codebase');
  sections.push('- Write clear, readable code with meaningful variable and function names');
  sections.push('- Add comments only for complex logic; code should be self-documenting');
  sections.push('- Handle errors appropriately; never silently swallow errors');
  sections.push('- Keep functions small and focused on a single task');

  if (scan.languages.some(l => l.name === 'TypeScript')) {
    sections.push('- Use proper TypeScript types; avoid `any` unless absolutely necessary');
    sections.push('- Prefer explicit return types on exported functions');
  }

  sections.push('');

  // LLM-enhanced sections (only present when --enhance was used)
  const enhanced = buildEnhancedSections(scan);
  if (enhanced) sections.push(enhanced);

  // Placeholder sections for manual customization
  sections.push('## Custom Rules');
  sections.push('');
  sections.push('<!-- Add your project-specific rules below -->');
  sections.push('');

  return {
    path: '.cursorrules',
    content: sections.join('\n'),
  };
}
