import {
  buildProjectOverview,
  buildStructureSection,
  buildConventionsSection,
  buildTestingSection,
  buildFrameworkGuidelines,
} from './shared.js';
import { buildEnhancedSections } from './enhanced.js';

/**
 * Generate .windsurfrules file
 * Windsurf uses a markdown-based rules file similar to Cursor.
 */
export function generateWindsurfRules(scan) {
  const sections = [];

  sections.push(`# Windsurf Rules — ${scan.project.name}`);
  sections.push(`# Generated by onboardai — ${new Date().toISOString().split('T')[0]}`);
  sections.push('');

  sections.push(buildProjectOverview(scan));
  sections.push(buildStructureSection(scan));

  const fwGuidelines = buildFrameworkGuidelines(scan);
  if (fwGuidelines) sections.push(fwGuidelines);

  sections.push(buildConventionsSection(scan));
  sections.push(buildTestingSection(scan));

  sections.push('## Rules');
  sections.push('');
  sections.push('- Follow existing code patterns and conventions');
  sections.push('- Write clean, well-documented code');
  sections.push('- Handle errors appropriately');

  if (scan.languages.some(l => l.name === 'TypeScript')) {
    sections.push('- Use strict TypeScript types; avoid `any`');
  }

  sections.push('');

  // LLM-enhanced sections
  const enhanced = buildEnhancedSections(scan);
  if (enhanced) sections.push(enhanced);

  return {
    path: '.windsurfrules',
    content: sections.join('\n'),
  };
}
